name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        build_type: ["Release", "Debug"]
        os: [macos-latest]
        compiler: [
            {
              type: gcc,
              version: 10,
              cc: gcc,
              cxx: g++,
            }
        ]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: |
          brew install ninja

    - name: Install gcc
      if: matrix.compiler.type == 'gcc'
      shell: bash
      run: |
          brew install gcc@${{matrix.compiler.version}}

    - name: Install packages
      working-directory: ${{ env.HOME }}
      shell: bash
      run: |
          CXX=${{matrix.compiler.cxx}}-${{matrix.compiler.version}} \
          CC=${{matrix.compiler.cc}}-${{matrix.compiler.version}} \
          vcpkg install gtest

    - name: Configure CMake
      shell: bash
      run: |
          VCPKG_ROOT=/usr/local/share/vcpkg \
          COMPILER_VERSION=-${{matrix.compiler.version}} \
          cmake --preset vcpkg-${{matrix.compiler.type}}

    - name: Build
      shell: bash
      run: |
        cmake \
            --build \
            --preset vcpkg-${{matrix.compiler.type}} \
            --config ${{matrix.build_type}}

    - name: Test
      shell: bash
      run: |
        ctest \
            --preset vcpkg-${{matrix.compiler.type}} \
            --config ${{matrix.build_type}}
